### ISSUE TITLE
TOC not in side bar in google-chrome

### ISSUE THREAD

**Issue by recifx** [vascoferreira25/ox-tailwind#1]
I git cloned the repo. However, when I open `~/Downloads/ox-tailwind/docs/another_theme.html` or any of the other html theme files in google-chrome on archlinux, the toc shows up on top not in a sidebar. It seems to work fine in Firefox and I did not check any other browsers.

Also I was not sure from the instructions on the home page on how to choose between the themes. 
I like the gitlab theme and would like to use it.

**Comment by vascoferreira25** [comment]
Hi,
The TOC shows up on top when the window has a small width. To use the theme, you just have to copy-paste the Gitlab theme settings to your settings file.

**Comment by recifx** [comment]
Hi,
I am not clear where the setting for the theme is. In the publish settings section, I see `:publishing-function org-tailwind-publish-to-html)`, but could not find any references to a theme. Could you post the index.org and auxillary org files needed to create one of the theme examples. Thanks.

**Comment by vascoferreira25** [comment]
After you load the `ox-tailwind.el` file in your Emacs config, you should be able to use the `Org Export Dispatcher` to export using this back-end. If you want to test how it works, clone this repository and open the `readme.org` file and open the `Org Export Dispatcher`. To launch the `Org Export Dispatcher` you can either use `Ctrl+c + Ctrl+e` or `, e e` with Spacemacs. You will see an option `[x] Export to HTML with org-tailwind Back-End`. By pressing `x h` it will generate an HTML file. Drag that file to `docs` folder and open it.

To use change the export theme you have to copy-paste the theme settings (in your case gitlab theme) to your Emacs config file. If you use Spacemacs, copy-paste the theme settings to the `(defun dotspacemacs/user-config ()` function.

**Comment by recifx** [comment]
I have it working now with the default theme. I see several `Error in parsing value for ...` in the browser console, and they seem to arise primarily from the mermaid and prism libraries, but they don't seem to affect the display of the elements, at least as far as I can tell.

I should be able to adapt my config (I am not using spacemacs or doom emacs) to use another theme. My understanding from looking over the code is that specific themes like gitlab override some of the settings of the default theme.

Thanks for your help and for making this project available.

**Comment by vascoferreira25** [comment]
If you see errors from Prism or Mermaid, it might be because you didn't have the HTML file in the dist folder. You can override all the class variables to change the theme. I made it this way because I thought it would be easier.

If you need anything just tell me 👍.

**Comment by recifx** [comment]
Hi,
I was unable to find the media setting to switch from the table-of-contents on top to on the side. On a 1920x1040 display it displays on the side in firefox but on top in both google-chrome stable and chromium on Archlinux. On a 3840x2160 display it is on the side in all three browsers.

I may be doing something wrong, but when I export to html using 'C-c C-e x h' in index.org with the recommended folder structure  the index.html file shows up in the same directory as index.org not in the dist folder.

My config is 
````
  (load "~/emacsd/straight/repos/ox-tailwind/ox-tailwind.el")
  (load "~/emacsd/tw_gl.el")
(setq org-publish-project-alist
      '(("org-files"
         :base-extension "org"
         :base-directory "~/Dropbox/tst/orgmode/"
         :publishing-directory "~/Dropbox/tst/orgmode/dist/"
         :publishing-function org-tailwind-publish-to-html)
        ("images"
         :base-directory "~/Dropbox/tst/orgmode/img/"
         :base-extension ".*"
         :publishing-directory "~/Dropbox/tst/orgmode/dist/img/"
         :publishing-function org-publish-attachment)
        ("files"
         :base-directory "~/Dropbox/tst/orgmode/files/"
         :base-extension ".*"
         :publishing-directory "~/Dropbox/tst/orgmode/dist/files/"
         :publishing-function org-publish-attachment)
        ("tangles"
         :base-directory "~/Dropbox/tst/orgmode/tangles/"
         :base-extension ".*"
         :publishing-directory "~/Dropbox/tst/orgmode/dist/tangles/"
         :publishing-function org-publish-attachment)
        ;; Publish all in one time
        ("notes" :components ("org-files" "images" "files" "tangles"))))
````
with the customization in 'tw_gl.el'
````
(setq org-tailwind--src-block-file-name
      "<div class=\"h-8 rounded-t flex %s\">
  <p class=\"mx-2 my-1 w-full text-center\">%s</p>
</div>"
![ox_tw](https://user-images.githubusercontent.com/6308104/98697018-baacd700-2374-11eb-9cf3-d2e8133b3ee8.png)
  )
(setq org-tailwind-head-files   "<!-- Tailwind CSS -->
<link href=\"./css/tailwind.min.css\" rel=\"stylesheet\"/>
....
````
The content display seems okay, with even the mermaid figures displaying correctly, but I am seeing the errors shown in the attached file in the chrome browsers. I am not sure if the components are being called from the prism.js file. I am using a custom prism.js and prism.css with the coy theme and the plugins you indicated.

Folder structure:
````
├── [rc              4096]  css
│   ├── [rc             10556]  org.css
│   ├── [rc             34765]  prism.css
│   ├── [rc               216]  style.css
│   └── [rc            710998]  tailwind.min.css
├── [rc              4096]  dist
│   ├── [rc              4096]  files
│   ├── [rc              4096]  img
│   └── [rc              4096]  tangles
├── [rc              4096]  docs
│   ├── [rc             52633]  another_theme.html
│   ├── [rc             52767]  dark.html
│   └── [rc             52376]  index.html
├── [rc              4096]  files
├── [rc              4096]  icons
│   └── [rc             27329]  folders.png
├── [rc              4096]  img
├── [rc             40924]  index.html
├── [rc             17371]  index.org
├── [rc             21620]  inx.org
├── [rc              4096]  js
│   ├── [rc             10662]  clipboard.min.js
│   ├── [rc           1128636]  mermaid.min.js
│   ├── [rc                72]  polyfill.min.js
│   ├── [rc            179676]  prism.js
│   └── [rc              2187]  toc_tree.js
├── [rc             10556]  org.css
├── [rc              4096]  sample_files
│   ├── [rc           3966137]  cat_treats.mp4
│   └── [rc           4612973]  weird_cat.gif
├── [rc             10906]  subjects_atp.html
├── [rc               121]  subjects_atp.org
├── [rc             12028]  subjects_math.html
├── [rc              1477]  subjects_math.org
└── [rc              4096]  tangles
````

**Comment by vascoferreira25** [comment]
Sorry that I was not clear. To the export to work as intended, you should `publish` your notes projects either by using `(org-publish-all)` or `(org-publish-all t)` to force the publishing. Although the `export` does also create an html file, it will not create it in the directory structure defined in the `org-publish-project-alist`, it will simple export it to the same folder as the org file. From what I can tell, the settings you showed are exactly as in the README and should work. Just try to `publish` the project instead of `exporting`. I will change the documentation to make it clearer and I will add an example folder to make it easier to use.

If it still doesn't work, try to do the following:

- Download this example project structure to a place of your choice: [notes_directory_example.zip](https://github.com/vascoferreira25/ox-tailwind/files/5518560/notes_directory_example.zip)
- In your config, write something like this (change the `base-directory` and `publishing-directory` path to the place where you have extracted the zip:

```
(setq org-publish-project-alist
      '(("notes"
         :base-extension "org"
         :base-directory "/path/notes_directory_example/"
         :publishing-directory "/path/notes_directory_example/dist/"
         :publishing-function org-tailwind-publish-to-html)))
```

- Open the `README.org` file and run the following command: `(org-publish-all)`
- If you check the `dist` folder, you should have a `README.html` file.

The settings that change the sidebar and content div behavior are the following:

```
(setq org-tailwind-class-sidebar "px-24 py-12 bg-gray-100
lg:border-r-4 lg:border-gray-300 lg:fixed lg:pt-2 lg:w-64 lg:px-2
lg:overflow-y-auto lg:inset-y-0 lg:mt-16")

(setq org-tailwind-class-content-container "flex-grow px-4 py-12 \
sm:px-8 md:px-12 lg:ml-64 lg:px-24 lg:overflow-x-auto xl:px-56")
```

If you read about Tailwind.CSS, you will notice that where it says `lg:....` means something that will happen on a larger screen size. To change that size to a smaller screen, change from `lg` to `md`.

Also, as you have said previously that you liked the gitlab theme, you can just copy-paste the gitlab theme settings right bellow the `org-publish-project-alist` settings and it should work.

**Comment by recifx** [comment]
Thanks for your patience on this. 
I had not tried `org-publish` earlier, but when I just tried it with the `notes` project, I get the error:
````
Publishing file /home/rc/Dropbox/tst/orgmode/index.org using ‘org-tailwind-publish-to-html’
helm-M-x-execute-command: Opening output file: No such file or directory, /home/rc/Dropbox/tst/orgmode/dist/js/toc_tree.js
````
I am not sure if it is something in my config with helm.

Running `org-publish` in the example project structure zip file you had linked does give the `readme.html` file in the `dist` folder. I will look into it some more and try to figure it out. Thanks again.

**Comment by vascoferreira25** [comment]
I don't mind at all. In fact I'm happy someone else liked this project. The error you get about `No such file or directory` happens because you were not editing an org file of that project.  Try opening an org file and try publishing it again. This happens to me too and I don't know yet why this happens.

**Comment by recifx** [comment]
I turned on 'debug on error' and when I run `org-publish` I get 
````
Debugger entered--Lisp error: (file-missing "Opening output file" "No such file or directory" "/home/rc/Dropbox/tst/orgmode/dist/js/toc_tree.js")
  write-region("" nil "/home/rc/Dropbox/tst/orgmode/dist//js/toc_tree.js")
  org-tailwind--json-toc-all-files("/home/rc/Dropbox/tst/orgmode/" "/home/rc/Dropbox/tst/orgmode/dist/")
  org-tailwind-publish-to-html((:base-extension "org" :base-directory "~/Dropbox/tst/orgmode/" :publishing-directory "~/Dropbox/tst/orgmode/dist/" :publishing-function org-tailwind-publish-to-html) "/home/rc/Dropbox/tst/orgmode/index.org" "/home/rc/Dropbox/tst/orgmode/dist/")
  org-publish-file("/home/rc/Dropbox/tst/orgmode/index.org" ("org-files" :base-extension "org" :base-directory "~/Dropbox/tst/orgmode/" :publishing-directory "~/Dropbox/tst/orgmode/dist/" :publishing-function org-tailwind-publish-to-html) t)
  org-publish-projects((("notes" :components ("org-files" "images" "files" "tangles"))))
  org-publish(("notes" :components ("org-files" "images" "files" "tangles")) nil nil)
  org-publish-current-project(nil nil)
  org-export-dispatch(nil)
  funcall-interactively(org-export-dispatch nil)
  call-interactively(org-export-dispatch nil nil)
  command-execute(org-export-dispatch)
````
Maybe this gives you some idea of what the issue may be. I will also look into it further.
I thought that the `toc_tree.js` file was generated by `org-tailwind-publish-to-html`. In the zip file that you linked, it seemed that this file was already present in the `dist/js/` directory.

 I just started out with trying to export org files to html and was glad to see this project which gives really nice output and which is, I  think, relatively straightforward to customize.

**Comment by vascoferreira25** [comment]
The `toc_tree.js` is generated and overwritten each time that you publish a project, that file is used on the search bar. You got an error while publishing because the you were not in a buffer in the notes folder. This happens because it uses the current directory to generate files. Even just opening `dired` in the notes folder and then publishing solves the problem.

As for customization, the only this back-end does is specifying classes on each type of block/markup so, if you don't like TailwindCSS, you can write your own CSS code in the `/dist/style.css` file.

**Comment by recifx** [comment]
I think the error was due to not having components in `org-publish-project-alist` to copy the css files to `dist/css` and the js files to `dist/js`. When I manually copied them, I was able to run `org-publish` from `index.org`, and it created `toc_tree.js` in `dist/js` as well as the `index.html`  and `subjects_....html` files in the `dist` directory.  When I click on one of the `subjects_...` links in `index.html`, it opens the correct html file, but with the toc empty. I can return to `index.html` by clicking on the  `Notes` title.

I am fine with using `tailwind.css` for long single page org files. It does get fairly verbose when writing raw html, but that is not an issue when the classes are generated from an org file. For multi-page files and for ease of navigation between them, it lacks UI components like navbars, but I will look into using `bulma.css` or `bootstrap` for such cases.

**Comment by vascoferreira25** [comment]
I guess that you were having problems because you started with an empty `dist` directory right? I'll write in the README file that when using this package everyone should just copy the example dist directory as it already has all the css/js files in it and only then publish the org files.

**Comment by recifx** [comment]
Yes, or to add components in `org-publish-project-alist` to copy the css files to `dist/css` and the js files to `dist/js`.

**Comment by vascoferreira25** [comment]
Very well. Should I consider this problem as fixed?

**Comment by recifx** [comment]
Yes, thanks for your help.
