### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by djgoku** [vascoferreira25/ox-tailwind#4]
Steps to reproduce:
1. git clone ox-tailwind
2. cd notes_example
3. edit index.org to match and execute this block
```emacs-lisp
(setq org-publish-project-list
      '(("notes-example"
         :base-extension "org"
         :base-directory "."
         :publishing-directory "./dist/"
         ;; :publishing-function org-tailwind-publish-to-html
)))
```
4. run `org-public-all` will succeed and export all projects and files.
5. now execute this block
```emacs-lisp
(setq org-publish-project-list
      '(("notes-example"
         :base-extension "org"
         :base-directory "."
         :publishing-directory "./dist/"
         :publishing-function org-tailwind-publish-to-html
)))
```
6. run `org-public-all` will error with `org-tailwind-paragragh: Symbol's function is void: equalp`

I know I am likely doing something wrong as I have never used tailwind and just trying to test using `org-publish` too.

Not really sure what I am doing wrong.

**Comment by vascoferreira25** [comment]
I noticed that this package throws errors when the line ends in `\\`. Do you perhaps have line that end with it? Please try to remove it and try again.

**Comment by vascoferreira25** [comment]
Anyways, I made a change in the package, please check if it works.
